# Generated by Django 4.2.1 on 2023-05-31 12:40

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_rename_sampletest_anothermetricfromtimescalemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateField(interval='1 day')),
                ('temperature', models.FloatField(default=0.0)),
                ('device', models.IntegerField(default=0)),
            ],
        ),
    ]
